import os
import datetime
from pathlib import Path
from typing import Dict, List

def save_memory(profile: Dict, analysis: str, gathered_data: List[str]):
    """
    Saves the hunt result as a Markdown file in the memories/ folder.
    This acts as an Obsidian note.
    """
    # Define vault path (relative to this file, assuming core/memory.py)
    # We want it in bakasura/memories
    vault_path = Path(__file__).parent.parent / "memories"
    
    # Ensure vault exists
    os.makedirs(vault_path, exist_ok=True)
    
    # Filename: YYYY-MM-DD_Name.md
    safe_name = "".join([c for c in profile['name'] if c.isalnum() or c in (' ', '_')]).strip().replace(' ', '_')
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_str}_{safe_name}.md"
    file_path = vault_path / filename

    # Metadata (Frontmatter)
    content = f"""---
created: {date_str}
tags: [bakasura, target, osint]
status: analyzed
target_name: {profile['name']}
---

# {profile['name']}

## Target Protocol (Dead Data)
- **City**: {profile.get('city', 'N/A')}
- **Country**: {profile.get('country', 'N/A')}
- **Phone**: {profile.get('phone', 'N/A')}
- **Handle**: {profile.get('nickname', 'N/A')}
- **Clues**: {profile.get('other_clues', 'N/A')}

## Bakasura Analysis
{analysis}

## Gathered Intelligence
"""
    
    for item in gathered_data:
        content += f"- {item}\n"
        
    # Append footer
    content += "\n\n---\n*Generated by Bakasura Protocol*"

    # Write to file
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    return str(file_path)
